#!/usr/bin/env python3
"""Generate Modular Paper 03: Finite Carrier and Information Dynamics."""

from _paper_template import PaperSpec, body, build_manuscript, bullet, equation, h1, h2, reference, statement

SPEC=PaperSpec(
    number=3,title="Finite Carrier and Information Dynamics",
    subtitle="Coherence, Resource-Gated Consolidation, and Exact Finite Allocation",
    filename="03_Finite_Carrier_and_Information_Dynamics.pdf",
    scope="The native nine-channel carrier and its finite information dynamics.",
    claim_boundary="Carrier dynamics and information accounting built on Papers 1 and 2.",
    sections=[("Abstract","Principal result."),("Native carrier","State and observables."),("Phase evolution","Route-cost dynamics."),("Decoherence correspondence","Contraction and Lindblad map."),("Consolidation","Low-energy state reduction."),("Information ledger","Semantic entropy and Landauer debit."),("Finite allocation","Largest-remainder quantization."),("Born-compatible measure","Error theorem and scope."),("Composite systems","Joint allocation and structural links."),("Conclusion","Information-dynamics result."),("References","Primary sources.")],
    document_label="INFORMATION DYNAMICS PAPER")

def manuscript(st):
    s=[
      h1("Abstract",st),
      body("Finite Possibility Mechanics represents local alternatives in a normalized nine-channel complex carrier rather than in independent scalar probabilities. Each carrier channel corresponds to one ordered pair of spatial route axes. Route cost acts on phase; carrier magnitudes determine immediate channel weights; coherence and binary probabilities are projections. When energy is sufficient, the carrier evolves continuously through phase rotation and dephasing. When available action falls below the consolidation gate, the runtime reduces maintainable alternatives, increases cache bias, quantizes channel weights onto a finite microcell population, and records the information discarded as a paid ledger term.",st),
      body("This paper proves three central results. First, the route-cost phase update preserves carrier norm exactly. Second, the selected dephasing update is a contraction and has the same stepwise form as a zero-Hamiltonian Lindblad pure-dephasing channel. Third, largest-remainder allocation preserves the exact microcell total and bounds every channel-count error below one cell, giving total-variation probability error at most m/(2N) for m channels and N microcells. For the FPM carrier, m=9 and N=1,452,997,909, so the universal bound is 3.10&times;10<sup>-9</sup>; the runtime audit observes 1.20&times;10<sup>-9</sup> over its declared trials.",st),
      statement("Information result","FPM supplies one finite mechanism for persistence, dephasing, consolidation, and discrete outcome weights. Decoherence removes phase coordination; consolidation removes maintainable alternatives. They are distinct operations with distinct ledger consequences.",st),
      body("<b>Record DOI:</b> <a href='https://doi.org/10.5281/zenodo.21420648'>https://doi.org/10.5281/zenodo.21420648</a>",st),
      h1("1. Native nine-channel carrier",st),
      equation("&psi;<sub>t</sub>=(&psi;<sub>1,t</sub>,...,&psi;<sub>9,t</sub>) in C<sup>9</sup>, &nbsp;&nbsp; &Sigma;<sub>a=1</sub><sup>9</sup>|&psi;<sub>a,t</sub>|<sup>2</sup>=1",st),
      body("Channel a labels one entry of the directed 3&times;3 route ledger. The carrier retains magnitude and phase. Immediate route weights are q<sub>a,t</sub>=|&psi;<sub>a,t</sub>|<sup>2</sup>; they are non-negative and sum to one. Phase contains relational information that a probability vector alone cannot store.",st),
      h2("1.1 Projected observables",st),
      body("A chosen partition of the nine channels defines binary projections p<sub>L</sub> and p<sub>R</sub>. A complex coherence projection c is formed from cross-channel phase relations, and dispersion is D=2|c|. These are observables of &psi;, not additional independently updated state. Changing the projection changes the observable without changing the carrier.",st),
      h2("1.2 Normalization invariant",st),
      statement("Proposition 1","If the carrier is normalized initially and every update is unitary phase rotation followed by explicit renormalization after a non-unitary branch, then its channel weights remain a probability measure at every committed tick.",st),
      h1("2. Route-cost phase evolution",st),
      equation("u<sub>a,i,t</sub>=|R<sub>a,i,t</sub>|/&Sigma;<sub>b=1</sub><sup>9</sup>|R<sub>b,i,t</sub>|, &nbsp;&nbsp; L<sub>a,i,t</sub>=L<sub>i,t</sub>u<sub>a,i,t</sub>",st),
      body("The nine entries of the site's directed route ledger provide the directional weights. If every |R<sub>a,i,t</sub>| is zero, the runtime uses u<sub>a,i,t</sub>=1/9. Consequently u<sub>a,i,t</sub>&ge;0, &Sigma;<sub>a</sub>u<sub>a,i,t</sub>=1, and &Sigma;<sub>a</sub>L<sub>a,i,t</sub>=L<sub>i,t</sub>. The channel phases therefore partition the action already debited from the site; they do not create nine additional action payments.",st),
      equation("&psi;<sub>a,t+1</sub>=&psi;<sub>a,t</sub> exp(-i&theta;L<sub>a,t</sub>)",st),
      body("L<sub>a,t</sub> is the channel's share of the site action and &theta; fixes the phase response per normalized action unit. The public runtime currently selects the dimensionless constitutive value &theta;=0.37; it is not derived from the carrier normalization theorem. Higher route burden accumulates phase faster. The update changes interference relations without changing a channel's magnitude. The runtime enforces the channel-sum identity on every call.",st),
      statement("Theorem 1 (Norm preservation)","For real &theta;L<sub>a,t</sub>, route-cost phase evolution preserves every |&psi;<sub>a</sub>| and therefore preserves ||&psi;||<sub>2</sub> exactly.",st),
      body("Proof. |exp(-i&theta;L)|=1 for real L. Hence |&psi;<sub>a,t+1</sub>|<sup>2</sup>=|&psi;<sub>a,t</sub>|<sup>2</sup> channel by channel; summation proves the result. QED.",st),
      h1("3. Decoherence correspondence",st),
      h2("3.1 Contractive coherence map",st),
      equation("c<sub>t+1</sub>=&kappa;<sub>t</sub>c<sub>t</sub>+&xi;<sub>t</sub>, &nbsp;&nbsp; 0&le;&kappa;<sub>t</sub>&le;1",st),
      equation("C<sub>N,t</sub>=min(w<sub>H,t</sub>H<sub>N,t</sub>+w<sub>S,t</sub>S<sub>N,t</sub>,1), &nbsp; g(e<sub>t</sub>)=e<sub>t</sub><sup>&chi;<sub>&rarr;</sub></sup>, &nbsp; &kappa;<sub>t</sub>=C<sub>N,t</sub>g(e<sub>t</sub>)",st),
      body("The lowercase c<sub>t</sub> is the coherence projection defined in Section 1.1. H<sub>N,t</sub> is normalized carrier entropy, S<sub>N,t</sub> is its balance score, and the nonnegative spectral weights satisfy w<sub>H,t</sub>+w<sub>S,t</sub>=1; the runtime obtains them from the singular values of the local route ledger. The normalized energy gate uses e<sub>t</sub> clipped to [0,1] and the declared exponent &chi;<sub>&rarr;</sub>=1/4. Thus 0&le;&kappa;<sub>t</sub>&le;1. The complex term &xi;<sub>t</sub> represents a declared internal or environmental coherence disturbance; it is not a new ledger currency. The optional reference routine enforces |&xi;<sub>t</sub>|&le;0.05e<sub>t</sub>+10<sup>-4</sup>.",st),
      statement("Theorem 2 (Dispersion contraction)","D<sub>t+1</sub>&le;&kappa;<sub>t</sub>D<sub>t</sub>+2|&xi;<sub>t</sub>|. For constant &kappa;&lt;1 and bounded |&xi;<sub>t</sub>|&le;&xi;<sub>max</sub>, limsup D<sub>t</sub>&le;2&xi;<sub>max</sub>/(1-&kappa;).",st),
      body("Proof. Apply the triangle inequality to c<sub>t+1</sub>, multiply by two, and iterate the resulting geometric inequality. QED.",st),
      body("This is a conditional contraction theorem for the declared affine coherence map. The production master-chain trajectory currently derives c from the updated carrier and does not inject the optional stochastic &xi;<sub>t</sub> branch. The Lindblad correspondence audit uses the controlled case &xi;<sub>t</sub>=0 with frozen &kappa;. A future noisy trajectory must publish the disturbance law, seed, and bound separately.",st),
      h2("3.2 Pure-dephasing map",st),
      equation("&rho;<sub>01,t+1</sub>=&kappa;&rho;<sub>01,t</sub>, &nbsp;&nbsp; &rho;<sub>00,t+1</sub>=&rho;<sub>00,t</sub>, &nbsp;&nbsp; &rho;<sub>11,t+1</sub>=&rho;<sub>11,t</sub>",st),
      body("For &kappa;=exp(-&Gamma;&Delta;t), this is the exact finite-step pure-dephasing channel generated by the Lindblad form with its Hamiltonian term held aside [1]. The FPM diagnostic compares this density-matrix update with the carrier-induced coherence update. The current numerical audit finds RMSE 1.79&times;10<sup>-102</sup> for the selected map, confirming algebraic identity in that channel.",st),
      statement("Distinction","Dephasing suppresses off-diagonal coordination while preserving the diagonal weights. It does not select or erase a channel. FPM consolidation is a later resource-gated operation.",st),
      h1("4. Resource-gated consolidation",st),
      body("Let e<sub>t</sub>=E<sub>t</sub>/E<sub>max</sub>. When e<sub>t</sub> falls below the declared consolidation threshold &epsilon;, the system cannot maintain the full active carrier at the required action floor. The runtime then applies a coupled transaction:",st),
      equation("&psi;&larr;reshape<sub>&pi;,&alpha;</sub>(&psi;), &nbsp;&nbsp; b&larr;clip(b+&beta;,0,1), &nbsp;&nbsp; E&larr;E-E<sub>erase</sub>",st),
      body("The reshape moves carrier weight toward the fallback prior &pi; by blend fraction &alpha;. Cache bias b increases, making recently retained structure more persistent. The final weights are placed on exact finite microcell counts. No observer command appears in this rule: the trigger is the node's own energy ledger.",st),
      h2("4.1 Constitutive status",st),
      body("The consolidation threshold, blend rate, and cache increment select the response of the finite carrier once the operation bound from Paper 1 becomes active. They are constitutive parameters recorded by the executable and exact-ledger papers. Their values are testable through sensitivity and regime-transition experiments.",st),
      h1("5. Semantic and thermodynamic information ledger",st),
      equation("S<sub>sem</sub>(q)=-&Sigma;<sub>a</sub>q<sub>a</sub> ln q<sub>a</sub>",st),
      body("S<sub>sem</sub> is a dimensionless Shannon entropy in nats. The distribution q is evaluated at the resolution of the consolidation transaction; for the binary projection q=(p<sub>L</sub>,p<sub>R</sub>). Define the across-update change explicitly by",st),
      equation("&Delta;S<sub>sem</sub>=S<sub>sem</sub>(q<sub>after</sub>)-S<sub>sem</sub>(q<sub>before</sub>)",st),
      equation("B<sub>erase</sub>=max(0,-&Delta;S<sub>sem</sub>/ln2)",st),
      body("B<sub>erase</sub> is the number of bit-equivalent distinctions removed by that consolidation. The dimensionless runtime records a normalized debit subject to available energy:",st),
      equation("E<sub>erase</sub><super>norm</super>=min[E,(B<sub>erase</sub>/N<sub>bit,eq</sub>)E<sub>max</sub>]",st),
      body("This normalized debit closes the executable ledger but is not, by itself, an SI derivation of Landauer heat. The dimensional bridge introduces a bath temperature T<sub>bath</sub>&gt;0 as an external constitutive or calibration input. It is not a local node state and is not derived by Papers 1-3. The current bridge default is T<sub>bath</sub>=300 K; changing it changes the dimensional heat linearly.",st),
      equation("Q<sub>min</sub>(T<sub>bath</sub>)=k<sub>B</sub>T<sub>bath</sub> ln2 &middot; B<sub>erase</sub>, &nbsp;&nbsp; &Delta;S<sub>bath</sub>/k<sub>B</sub>&ge;B<sub>erase</sub>ln2",st),
      statement("Theorem 3 (Dimensionless entropy closure)","If B<sub>erase</sub>=-&Delta;S<sub>sem</sub>/ln2 distinctions are removed and the bath satisfies Landauer's bound, then &Delta;S<sub>sem</sub>+&Delta;S<sub>bath</sub>/k<sub>B</sub>&ge;0. Equality holds at the ideal minimum; additional dissipation makes the sum positive.",st),
      body("The division by k<sub>B</sub> is essential: it compares two dimensionless quantities. The theorem connects semantic and bath ledgers without identifying them. The runtime audit now derives B<sub>erase</sub> from the measured before-and-after entropy change and verifies the equality case in these normalized units.",st),
      h1("6. Exact finite allocation",st),
      body("Given target probabilities q<sub>1</sub>,...,q<sub>m</sub> and an integer capacity N, set x<sub>a</sub>=Nq<sub>a</sub>. Assign f<sub>a</sub>=floor(x<sub>a</sub>) cells, then distribute the remaining N-&Sigma;f<sub>a</sub> cells to the largest fractional remainders. Ties are resolved by a declared stable ordering.",st),
      statement("Theorem 4 (Largest-remainder conservation)","The allocation returns integers n<sub>a</sub>&ge;0 with &Sigma;n<sub>a</sub>=N and |n<sub>a</sub>-Nq<sub>a</sub>|&lt;1 for every channel.",st),
      body("Proof. The floors allocate no more than N. Each remaining cell increments one of the largest positive remainders. No channel differs from its floor by more than one, and the number assigned is exactly the floor deficit. QED.",st),
      statement("Corollary 4.1 (Finite probability bound)","For p<sub>a</sub>=n<sub>a</sub>/N, |p<sub>a</sub>-q<sub>a</sub>|&lt;1/N and total-variation distance D<sub>TV</sub>(p,q)&lt;m/(2N).",st),
      equation("m=9, N=1,452,997,909; therefore D<sub>TV</sub>&lt;3.10&times;10<sup>-9</sup>",st),
      h2("6.1 Carrier-radius and capacity provenance",st),
      body("The finite capacity N is not an independently inserted decimal. It is obtained from the selected four-step shell construction for the dimensionless carrier radius &alpha;<sub>PP</sub>. The closed shells n=1,...,9 contribute",st),
      equation("C<sub>&le;9</sub>=&Sigma;<sub>n=1</sub><sup>9</sup>2n<sup>2</sup>=570, &nbsp;&nbsp; C<sub>10</sub>=2(10)<sup>2</sup>=200.",st),
      body("The tenth shell contributes its selected transverse fraction 2/3, and the two-blade boundary subtracts 1/sqrt(2). Define",st),
      equation("a<sub>1</sub>=570+(2/3)200-1/&radic;2.",st),
      body("Finite endcap backreaction and the second-order boundary term then define &alpha;<sub>PP</sub> as the positive fixed point",st),
      equation("&alpha;<sub>PP</sub>=a<sub>1</sub>+(3/2)/(&alpha;<sub>PP</sub>+9)+(15/2-L<sub>rest</sub>)/(&alpha;<sub>PP</sub>+9)<sup>2</sup>.",st),
      statement("Proposition 4.2 (Carrier-radius fixed point)","For the declared shell prescription and L<sub>rest</sub>=0.1030625, the iteration converges to &alpha;<sub>PP</sub>=702.6283490004513. Direct substitution into the fixed-point equation gives zero residual in the evaluated binary64 arithmetic.",st),
      body("This value is a derived output of the stated finite-carrier prescription, not a measured calibration or emergent trajectory statistic. The shell occupation, transverse fraction, blade subtraction, and boundary-counterterm form are constitutive geometric choices; once they are fixed, the fixed point is mathematically determined. The exact microcell capacity is then the integer cubic-lattice count",st),
      equation("N=|{(i,j,k) in Z<sup>3</sup>: i<sup>2</sup>+j<sup>2</sup>+k<sup>2</sup>&le;&alpha;<sub>PP</sub><sup>2</sup>}|=1,452,997,909.",st),
      h1("7. Born-compatible finite measure",st),
      equation("q<sub>a</sub>=|&psi;<sub>a</sub>|<sup>2</sup>/&Sigma;<sub>b</sub>|&psi;<sub>b</sub>|<sup>2</sup>, &nbsp;&nbsp; P<sub>FPM</sub>(a)=n<sub>a</sub>/N",st),
      body("The carrier magnitudes supply the Born weights [3] and largest-remainder allocation supplies their finite realization. A global phase rotation leaves every q<sub>a</sub> unchanged. The numerical audit tests random normalized carriers and phase rotations, reporting maximum total-variation error 1.20&times;10<sup>-9</sup>, inside the theorem's universal bound.",st),
      h2("7.1 Measurement basis",st),
      body("The direct bridge quantizes the nine native channel weights. A general detector orientation requires a specified basis transformation U before allocation, q<sub>a</sub>=|(U&psi;)<sub>a</sub>|<sup>2</sup>. This is the precise extension required for arbitrary contextual measurements; it does not alter the finite-allocation theorem.",st),
      h1("8. Composite carriers and shared structural links",st),
      body("Independent allocation of two local carriers produces a Bell-local baseline. FPM's joint-torsion bridge instead treats an explicitly linked pair as one allocation transaction whose probabilities are computed after rotating the two local route frames. The shared boundary is a declared nonlocal resource in Bell's sense, not a hidden local variable. Paper 5 derives the joint correlation and Paper 6 fixes its experimental failure conditions.",st),
      body("At the implementation level, joint allocation uses the same exact finite-count rule as the single carrier. The regenerated standard run executes 1,921 linked joint quantizations with maximum observed total-variation error 4.29&times;10<sup>-10</sup>.",st),
      h1("9. Conclusion",st),
      body("The FPM carrier turns directed possibilities into a finite dynamical object. Route cost changes phase without changing norm; environmental or internal disturbance contracts coherence; resource pressure activates a separate consolidation transaction; erased distinctions enter a thermodynamic ledger; and continuous target weights become exact integer populations with a rigorous error bound. The construction therefore connects coherence and finite information capacity without conflating decoherence, selection, and erasure.",st),
      statement("Carrier summary","Possibility persists as phase-coherent finite state while the energy ledger can maintain it. When it cannot, FPM consolidates explicitly, pays for discarded distinctions, and records the surviving distribution exactly.",st),
      h1("References",st),
      reference("[1] G. Lindblad, “On the Generators of Quantum Dynamical Semigroups,” <i>Communications in Mathematical Physics</i> 48, 119–130 (1976). <a href='https://doi.org/10.1007/BF01608499'>https://doi.org/10.1007/BF01608499</a>",st),
      reference("[2] R. Landauer, “Irreversibility and Heat Generation in the Computing Process,” <i>IBM Journal of Research and Development</i> 5, 183–191 (1961). <a href='https://doi.org/10.1147/rd.53.0183'>https://doi.org/10.1147/rd.53.0183</a>",st),
      reference("[3] M. Born, “Zur Quantenmechanik der Stoßvorgänge,” <i>Zeitschrift für Physik</i> 37, 863–867 (1926). <a href='https://doi.org/10.1007/BF01397477'>https://doi.org/10.1007/BF01397477</a>",st),
      reference("[4] A. Spiker, <i>FPM Foundations: Finite Local Substrates, Directed Route Ledgers, and Exact Closure</i>, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21420508'>https://doi.org/10.5281/zenodo.21420508</a>",st),
      reference("[5] A. Spiker, <i>Executable FPM: Reference Runtime, Numerical Contract, and Reproducible Audit</i>, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21420643'>https://doi.org/10.5281/zenodo.21420643</a>",st),
      reference("[6] A. Spiker, <i>Finite Possibility Mechanics: A Unified Information-Theoretic Framework</i>, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21352386'>https://doi.org/10.5281/zenodo.21352386</a>",st),
      reference("[7] A. Spiker, <i>Finite-Possibility-Mechanics-Complete</i>, carrier and allocation reference implementation. <a href='https://github.com/alxspiker/Finite-Possibility-Mechanics-Complete'>https://github.com/alxspiker/Finite-Possibility-Mechanics-Complete</a>",st),
    ]
    return s

if __name__=="__main__": print(build_manuscript(SPEC,manuscript))
