#!/usr/bin/env python3
"""Generate Modular Paper 04: Tensorless Exact-Ledger Sandbox."""

from reportlab.platypus import PageBreak
from _paper_template import PaperSpec,body,build_manuscript,bullet,equation,h1,h2,reference,statement

SPEC=PaperSpec(number=4,title="Tensorless Exact-Ledger Sandbox",subtitle="Deterministic Integer Policies and Their Boundary with Reference FPM",filename="04_Tensorless_Exact_Ledger_Realization.pdf",scope="The exact integer ledger sandbox and its explicit constitutive policies.",claim_boundary="Tensorless proves exact closure for its represented integer transaction. It does not yet implement Paper 1's ordinary nearest-neighbour replenishment kernel.",sections=[("Abstract","Exact-ledger result and conformance boundary."),("Design objective","From real-valued reference to deterministic transaction."),("Exact units","One-third-micro-action arithmetic."),("Synchronous transaction","Snapshot, contention, commit, and audit."),("R1 replenishment","Exact global activity pressure allocation."),("N1 route exchange","Conservative stochastic route kernel."),("Q1 quantization","Finite route quantum."),("Conservation theorems","Energy, momentum, and route sums."),("Parameter provenance","Fixed, derived, free, and fitted values."),("Reference correspondence","Shared contracts and known differences."),("Conclusion","Exact-ledger result."),("References","Implementation sources.")],document_label="EXACT-LEDGER PAPER")

def manuscript(st):
 s=[
 h1("Abstract",st),body("Tensorless provides a deterministic exact-ledger sandbox for FPM-inspired finite-resource dynamics. Its synchronous sandbox represents energy and action in exact one-third-micro-action subunits, route cost in an unsigned 3&times;3 integer ledger, and momentum in a separate signed 3&times;3 ledger. Each tick is a snapshot transaction: reserve action, form payload and momentum proposals, resolve competing capacity claims globally, commit accepted transfers simultaneously, record rejected transfers externally, and close the action-replenishment ledger. Successful ticks verify energy and momentum identities with integer residual zero.",st),
 body("Exact ledger closure is not the same claim as exact conformance to every transition in the Python reference. The current Tensorless paper-ledger function allocates the total action globally in proportion to activity weights, whereas Papers 1 and 2 define ordinary one-tick replenishment through the nearest-neighbour kernel r=P<super>T</super>L. Tensorless therefore realizes an exact equilibrium-style signed ledger under its own declared contract; it is not yet an exact integer implementation of the complete local transport dynamics.",st),
 body("Three constitutive policies make the continuous-to-discrete contract explicit. R1 defines an integer activity pressure from six-face viscosity contrast and prior-target mismatch. N1 defines reproducible one-quantum antisymmetric route exchanges gated by mobility and paid action. Q1 fixes the normalized route quantum at 10<sup>-6</sup>. These policies are not numerical patches: they specify how the finite engine resolves choices that a real-valued equation leaves underdetermined. Their status is declared, their ordering is deterministic, and their global invariants are proved below.",st),
 statement("Exact-ledger result","The engine eliminates floating-point conservation drift from its represented core. Every accepted unit, rejected unit, starvation deficit, and momentum share occupies an integer account, and every successful tick closes exactly.",st),
 h1("1. Design objective",st),body("The Python simulator is the readable reference semantics. Tensorless answers a different question: what additional rules are required to execute the same finite-resource ideas with exact arithmetic, simultaneous contention, deterministic replay, and no tolerance-based conservation decision?",st),
 body("A real-valued specification does not uniquely determine how fractional shares are rounded, how ties are ordered, when action is reserved relative to payload, how competing sources share a nearly full target, or how random route exchange consumes its stream. Tensorless elevates these choices into named operational policies. It is a separate exact policy realization, not an automatic completion of every Python transition: different policies define different finite engines even when they share selected state variables and conservation goals.",st),
 h2("1.1 Core and adapter boundary",st),bullet("The core owns bounded state, transport, ledgers, deterministic scheduling, and diagnostics.",st),bullet("The caller supplies the integer translation of the complete per-node Lagrangian and payload request.",st),bullet("Adapters assign physical, computational, chemical, or other domain meaning outside the core.",st),bullet("The parameter ledger records declared provenance so operational choices cannot disappear into source code.",st),
 h2("1.2 Sandbox momentum extension",st),body("Tensorless adds a signed integer state M<sub>i</sub>&isin;Z<sup>3&times;3</sup> for payload-flow bookkeeping. This momentum ledger is an adapter-facing extension of the sandbox state; it is not the unsigned route-cost ledger R, is not part of the Paper 2 reference state vector, and is not derived from the five foundational axioms. The core never converts M into energy or action. Action is reserved and closed in its own ledger, while a caller-selected transport fraction determines how much signed M accompanies a payload proposal.",st),
 body("During contention, the transferable signed momentum is partitioned once across the finally accepted payload destinations and one rejected-payload destination. Accepted shares enter target momentum and rejected shares enter the external momentum account. The resulting zero residual proves conservation of this represented integer bookkeeping variable under the sandbox transaction. A physical identification with mechanical momentum requires an adapter-specific units map and correspondence test; it is not established by the integer identity alone.",st),
 h1("2. Exact units",st),equation("1 action = 1,000,000 micro-actions = 3,000,000 sandbox subunits",st),body("One sandbox subunit is exactly one third of a micro-action. The normalized FPM energy ceiling 2/3 action is therefore the integer 2,000,000 subunits. The action floor c<sub>0</sub>=0.05 action is exactly 150,000 subunits.",st),
 equation("Q<sub>action</sub>(c<sub>0</sub>)=3&times;50,000=150,000 subunits",st),statement("Proposition 1 (Exact representability)","Every integer micro-action value, the 2/3-action ceiling, and the 0.05-action floor are integers in the one-third-micro-action unit. No rounding is required for these core quantities.",st),
 body("The factor three is a unit conversion, not three separate c<sub>0</sub> charges. This prevents a common accounting error when comparing the exact sandbox with the real-valued reference.",st),
 h1("3. Synchronous tick transaction",st),h2("3.1 Snapshot discipline",st),body("All proposals are computed from the same pre-tick snapshot. No source can observe a neighbour's partially committed transfer. This gives the tick an unambiguous simultaneous semantics and removes dependence on loop order.",st),
 h2("3.2 Reservation and contention",st),bullet("Validate state ranges, locks, action floors, and affordability.",st),bullet("A source with nonzero payload must reserve action first: payload + action &le; snapshot energy.",st),bullet("Scatter payload and momentum proposals to the six face slots.",st),bullet("Resolve all sources competing for each target against its remaining capacity.",st),bullet("Split momentum once, in proportion to final accepted face energies plus one rejected-energy destination.",st),bullet("Commit accepted transfers simultaneously and move rejected portions to external ledgers.",st),bullet("Run exact action debit, replenishment, local spillover, exhaust, and starvation accounting.",st),
 h2("3.3 Largest-remainder contention",st),body("If a target cannot accept every offer, integer shares are assigned by floor division and remaining units are distributed in this total order: remainder descending; offered payload descending; source flat index ascending; source face ascending. The order is part of the engine definition and guarantees replay across platforms.",st),
 statement("Theorem 1 (Contention conservation)","Largest-remainder contention assigns exactly min(total offered, target capacity) energy units. No source receives a negative share and no target exceeds capacity.",st),body("Proof. Floor shares never exceed the requested total. Each residual unit is assigned only to an open positive-weight claimant, and saturated claimants are removed before recomputation. The loop ends when the accepted sum reaches the lesser of demand and capacity or no capacity remains. QED.",st),
 h1("4. Constitutive replenishment R1",st),body("R1 converts normalized observables into exact activity pressure without an intermediate integer mean. The ABI field &pi;<sub>i</sub> is the integer encoding of the fallback prior &pi;<sub>i</sub> used in Papers 1-3, while the ABI field &tau;<sub>i</sub> encodes their local target T<sub>i</sub>:",st),equation("W<sub>i</sub>=&Sigma;<sub>six faces f</sub>|&Omega;<sub>i</sub>-&Omega;<sub>n(i,f)</sub>| + 6|&pi;<sub>i</sub>-&tau;<sub>i</sub>|",st),
 body("Periodic face multiplicity is retained. The first term is exactly proportional to six times the neighbour-mean viscosity contrast; the second gives the same six-face scale to prior-target mismatch. If all W<sub>i</sub> vanish, every weight is set to one, the unique permutation-symmetric positive fallback.",st),
 statement("Proposition 2 (R1 symmetry)","On a completely homogeneous state, R1 assigns identical positive weight to every node. Relabelling nodes leaves the replenishment allocation unchanged.",st),body("The current paper-ledger function first sums the complete action debit and then uses an exact largest-remainder allocator to distribute that total in proportion to W:",st),
 equation("r<sub>i</sub><super>R1</super> = Allocate<sub>integer</sub>[(&Sigma;<sub>j</sub>L<sub>j</sub>)W<sub>i</sub>/(&Sigma;<sub>k</sub>W<sub>k</sub>)]",st),
 body("This allocation is global: changing one node's W can change another node's replenishment in the same sandbox tick even when the nodes are not neighbours. R1 therefore defines an exact equilibrium-style closure, not Paper 1's finite-speed microscopic law. The six-face geometry enters the weights, but it does not make the subsequent normalization local. An exact implementation of r=P<super>T</super>L remains a separate conformance task.",st),
 h1("5. Constitutive route exchange N1",st),body("N1 represents closed thermal route fluctuations as antisymmetric one-quantum exchanges across edges. Edge slots are visited in flat-node order, then +x,+y,+z, then channel order. Every slot consumes two PCG32 values [4]: an activation roll and a direction bit, even if the exchange is inactive or vetoed.",st),
 body("For each node i, m<sub>i</sub>&isin;{0,...,10<sup>6</sup>} is the normalized integer mobility observable supplied through the sandbox adapter. Thus m<sub>i</sub>/10<sup>6</sup> is the node's N1 activation scale. It is a node-level policy input, not automatically the link mobility &mu;<sub>ij</sub> of Paper 1; an adapter claiming that correspondence must publish the map from its FPM mobility calculation to m<sub>i</sub>.",st),
 equation("m<sub>edge</sub>=min(m<sub>A</sub>,m<sub>B</sub>), &nbsp; cutoff=floor(m<sub>edge</sub>2<sup>32</sup>/10<sup>6</sup>)",st),
 equation("exchange iff uint32_roll &lt; cutoff",st),
 body("An activated exchange subtracts one Q1 unit from one endpoint's channel and adds one to the other. It is vetoed at either route boundary, on a self-loop, or unless both endpoints supplied and could afford at least one c<sub>0</sub> action floor for the tick. N1 belongs to the already-paid route-candidate-evaluation operation; it does not add a separate fee per trial.",st),
 statement("Theorem 2 (N1 route-sum conservation)","For every channel, every accepted N1 exchange preserves the global unsigned route-cost sum exactly.",st),body("Proof. One endpoint changes by -1 and the other by +1 in the same channel. Vetoed exchanges change neither. Summing over any sequence of trials gives zero net change. QED.",st),
 h1("6. Route quantization Q1",st),equation("policy_scale=1,000,000, &nbsp;&nbsp; q<sub>R</sub>=1/policy_scale=10<sup>-6</sup>",st),
 body("Q1 fixes the representable normalized route interval to integer values 0 through 1,000,000. It is the lattice spacing of the route ledger in the constitutive modes. Its value determines resolution, state count, and N1 trial probability; changing it defines a different exact realization and must change the parameter fingerprint.",st),
 statement("Proposition 3 (Route bounds)","N1 plus its boundary veto leaves every normalized route channel in the closed integer interval [0,policy_scale].",st),
 h1("7. Exact conservation identities",st),h2("7.1 Energy",st),equation("E<sub>initial</sub>=E<sub>current</sub>+E<sub>external</sub>-E<sub>starvation</sub>",st),
 body("External exhaust contains energy removed from represented nodes by rejected or unrouteable transfers. Starvation is subtracted because clipping an unaffordable negative raw balance to zero raises stored energy relative to the ideal signed update. The signs match the expanded ledger proved in Paper 1. Tensorless computes the originating node event during the transaction but exposes cumulative aggregate exhaust and starvation counters; it does not currently retain the Python runtime's full site-by-tick event history.",st),
 statement("Theorem 3 (Integer energy closure)","If a sandbox tick returns success, the energy identity holds with integer residual exactly zero and every node satisfies 0&le;E<sub>i</sub>&le;E<sub>ceiling</sub>.",st),
 h2("7.2 Momentum",st),equation("M<sub>initial,c</sub>=M<sub>current,c</sub>+M<sub>external,c</sub> &nbsp; for each of nine channels c",st),
 body("Accepted momentum enters the target; rejected momentum enters the external account. Quantizing only after contention ensures accepted and rejected shares partition the source's transferable momentum once, avoiding compounded rounding.",st),
 statement("Theorem 4 (Integer momentum closure)","If a sandbox tick returns success, all nine signed momentum identities have residual exactly zero.",st),
 h2("7.3 Thermal noise boundary",st),body("Independent additive momentum noise is excluded from the exact sandbox because no closed paper-specified noise ledger currently balances it. N1 supplies a closed route fluctuation, not a momentum-noise substitute. This preserves exactness instead of hiding an unbalanced random term behind tolerance.",st),
 h1("8. Parameter provenance",st),body("Every declared run parameter can be classified FIXED, DERIVED, FREE, or FITTED. The parameter ledger records name, full-precision value, class, and source; sorts entries canonically; and computes a 64-bit FNV-1a drift fingerprint over core identity, hashes, and entries.",st),
 bullet("FIXED: selected before the run and held constant.",st),bullet("DERIVED: computed from fixed inputs.",st),bullet("FREE: selected by caller or adapter without fitting to the evaluated data.",st),bullet("FITTED: adjusted against data.",st),
 body("The fingerprint detects declared drift; it is intentionally non-cryptographic and does not replace archival hashes or signatures. Its scientific purpose is to make parameter changes visible and to distinguish a fixed constitutive policy from a fitted adapter coefficient.",st),
 h1("9. Correspondence with the Python reference",st),body("The two runtimes share the finite cubic geometry, 3&times;3 route ledger, bounded energy, signed starvation and exhaust accounts, finite carrier concepts, and local-capacity routing. They differ in representation, scheduling, retained diagnostics, and operational kernels. Correspondence must therefore be claimed contract by contract.",st),
 bullet("Python evaluates real-valued equations directly; Tensorless executes integer transactions.",st),bullet("Python ordinary replenishment uses the local reversible P<super>T</super>L kernel; the Tensorless paper-ledger function and R1 modes use exact proportional allocation under their declared contract.",st),bullet("Python phase evolution uses complex arithmetic; Tensorless stores scaled carrier and route state.",st),bullet("Tensorless defines contention order, random-stream consumption, action reservation, and momentum partition exactly.",st),
 bullet("Python retains site-resolved exhaust, starvation, and Landauer event increments; Tensorless currently exposes cumulative aggregate counters.",st),bullet("Python derives its Lagrangian and carrier transitions internally; the Tensorless sandbox receives caller-translated action and payload values.",st),
 statement("Cross-runtime audit target","Agreement is required only for a named shared contract and an explicit continuous-to-discrete input map. Exact zero residual in Tensorless proves its represented ledger identity; it does not by itself prove trajectory equivalence, the local kernel, carrier equivalence, or a physical interpretation. Differences caused by R1, N1, or Q1 are policy effects to measure, not floating-point errors to conceal.",st),
 h1("10. Conclusion",st),body("Tensorless demonstrates that an FPM-inspired finite-resource transaction can be executed with exact conservation, bounded state, deterministic contention, and reproducible stochastic route exchange. The additional rules are visible: one-third-micro-action units make the core scales integral; R1 defines a global activity-weighted allocator; N1 defines paid, conservative route fluctuation; and Q1 defines route resolution. Their explicitness turns implementation ambiguity into a testable model family while leaving local-kernel conformance as an open engineering obligation.",st),
 statement("Exact-ledger summary","Tensorless does not merely round the Python simulator. It defines a distinct exact transaction whose represented energy and momentum ledgers close identically. That result is strong but scoped: the current sandbox is not yet the exact-integer form of every FPM transition.",st),
 PageBreak(),h1("References",st),reference("[1] A. Spiker, <i>Tensorless Engine: Experimental Synchronous FPM Sandbox</i>, private source documentation and implementation, files <font face='Courier'>docs/fpm-sandbox.md</font>, <font face='Courier'>core/src/tensorless_sandbox.cpp</font>, and <font face='Courier'>core/src/tensorless_ledger.cpp</font> (accessed July 2026).",st),reference("[2] A. Spiker, <i>FPM Foundations</i>, Modular Paper 01.",st),reference("[3] A. Spiker, <i>Executable FPM</i>, Modular Paper 02.",st),reference("[4] M. E. O’Neill, “PCG: A Family of Simple Fast Space-Efficient Statistically Good Algorithms for Random Number Generation,” Harvey Mudd College technical report HMC-CS-2014-0905 (2014). https://www.pcg-random.org/paper.html",st)
 ];return s

if __name__=="__main__":print(build_manuscript(SPEC,manuscript))
