#!/usr/bin/env python3
"""Generate Modular Paper 06: Empirical Audit and Falsification."""

from reportlab.platypus import PageBreak

from _paper_template import (
    PaperSpec, body, build_manuscript, bullet, equation, h1, h2, reference,
    statement,
)


SPEC = PaperSpec(
    number=6,
    title="Empirical Audit and Falsification",
    subtitle="Evidence Levels, Reproduction Standards, and Decisive Tests for FPM",
    filename="06_Empirical_Audit_and_Falsification.pdf",
    scope="The evidence architecture and pre-committed failure programme for FPM.",
    claim_boundary="A test receives exactly the evidential weight warranted by its inputs and design.",
    sections=[],
    document_label="AUDIT PAPER",
)


def manuscript(st):
    s = [
        h1("Abstract", st),
        body("Finite Possibility Mechanics is unusually testable because its mathematical, computational, and phenomenological layers can be audited separately. This paper defines that audit architecture. It distinguishes proof, implementation verification, numerical correspondence, calibration, retrospective empirical comparison, and prospective prediction; reports the current executable suite; specifies reproducibility requirements; and fixes the failure logic for the framework's highest-value physical tests.", st),
        body("The current public suite contains sixteen primary experiments plus one starvation subtest. It verifies local transport, signed conservation, carrier contraction, finite probability allocation, joint torsion quantization, fixed algebraic constructions, and bridge calculations. These are implementation and algebraic checks of the supplied model; they do not independently establish physical mechanism. Temperature, paid link maintenance, clock progress, and cosmological transfer dynamics are candidate extensions with additional stated dependencies.", st),
        statement("Audit result", "FPM has a reproducible computational foundation and a sharply defined empirical frontier. The framework advances by keeping foundational results, calibrated maps, constitutive bridges, and candidate extensions visibly separate.", st),
        body("<b>Record DOI:</b> <a href='https://doi.org/10.5281/zenodo.21420655'>https://doi.org/10.5281/zenodo.21420655</a>", st),

        h1("1. Evidence hierarchy", st),
        body("Every reported result is assigned one evidence level. Higher levels depend on lower ones but do not retroactively change their meaning.", st),
        bullet("<b>Level 1 — Formal result.</b> A theorem follows from explicit premises by mathematical proof.", st),
        bullet("<b>Level 2 — Implementation invariant.</b> Code satisfies an identity, bound, ordering rule, or reproducibility contract.", st),
        bullet("<b>Level 3 — Correspondence audit.</b> An FPM update reproduces the form or numerical output of a selected established equation.", st),
        bullet("<b>Level 4 — Calibration audit.</b> A dimensional bridge uses measured input and returns a target scale; sensitivity to the calibration is part of the result.", st),
        bullet("<b>Level 5 — Retrospective empirical comparison.</b> A fixed map is evaluated on existing observations with declared selection and nuisance treatment.", st),
        bullet("<b>Level 6 — Prospective discriminating test.</b> Inclusion rules, parameters, likelihood, and failure threshold are fixed before the decisive data are evaluated.", st),
        body("A unit test passing means the implementation obeyed the tested contract. A correspondence passing means two specified calculations agreed. Neither statement alone means nature selected FPM. Conversely, an empirical failure of one observable map need not invalidate a theorem about local conservation. The hierarchy localizes both success and failure.", st),
        statement("Interpretation rule", "The word PASS is always qualified by the test level. No label may silently move a result upward in the hierarchy.", st),
        h2("1.1 Candidate extension boundary", st),
        body("Axioms A1-A5 determine the finite substrate, bounded route cost, closed accounting, ordered ticks, and speed calibration. They do not determine a Kelvin-valued state temperature, a paid maintenance rule for a pure-gauge torsion link, a progress scheduler for a physical clock, or a cosmological oscillator. Each is a candidate extension program. Conditional algebra following an adopted postulate is a Level 1 result relative to that postulate; it becomes a Level 6 result only through a registered experiment.", st),
        body("For the proposed canonical-temperature diagnostic, the first master-chain action state is evaluated after the tick-zero truth-target update and before replenishment. Its 375 undirected edges give corr(Delta L, ln[P<sub>ij</sub>/P<sub>ji</sub>])=0.00469041, beta*= -0.00183473, and normalized residual 0.99999401. The result rejects a scalar canonical temperature for that state under the proposed edge criterion; it does not select a replacement temperature law. The candidate nine-channel equipartition postulate instead divides E<sub>max</sub> equally across the native directed carrier channels, giving T=306.442 K and G<sub>FPM</sub>=6.53990x10<super>-11</super> in the implemented dimensional map; its 2.0137 percent CODATA difference remains an unresolved discrepancy.", st),

        h1("2. Reproducibility contract", st),
        h2("2.1 Required research objects", st),
        bullet("Immutable source revision or archival source bundle, plus the exact generator command.", st),
        bullet("Machine-readable parameter ledger with every value classified fixed, derived, free, or fitted.", st),
        bullet("Input data identifiers, checksums, licenses, inclusion filters, and unit transformations.", st),
        bullet("Runtime language and dependency versions, platform information, random seed, and random-stream policy.", st),
        bullet("Raw outputs, summary JSON, chart-generation script, and the final paper generator.", st),
        bullet("A comparison report that names the reference model, metric, uncertainty treatment, and decision rule.", st),
        body("These objects follow the FAIR research-data principles [6]: results must be findable, accessible under their applicable permissions, interoperable enough to inspect, and reusable with preserved provenance. Private inputs may remain private, but their hashes, interface contracts, and access conditions must still be recorded.", st),
        h2("2.2 Deterministic and stochastic runs", st),
        body("Deterministic tests must reproduce bit-for-bit when their platform contract promises exact arithmetic, or within a declared tolerance when IEEE binary floating point [7] is part of the implementation. Stochastic tests must publish the generator, seed, stream-consumption order, sample count, estimator, and confidence interval. A single fixed seed is a replay test, not an uncertainty analysis.", st),
        h2("2.3 Current public artifact", st),
        body("The public repository places Python generators in the scripts directory, generated JSON in outputs, and audit charts in their chart directory. The main experiment uses a finite periodic 5 by 5 by 5 cubic lattice: 125 nodes, six face neighbours per node, and 400 ticks. The JSON is an auditable result object, but a stored benchmark is not equivalent to a live rerun when its external dataset is absent. In particular, the public SPARC record is archived, unregenerated metadata and receives no empirical evidence level until the dataset, selection ledger, parameter ledger, source revision, and regenerated outputs are available together.", st),
        h2("2.4 Cross-runtime conformance", st),
        body("The Python reference and Tensorless exact-ledger sandbox are not presumed trajectory-equivalent. Python executes ordinary replenishment with the nearest-neighbour kernel r=P<super>T</super>L and retains site-resolved event histories. Tensorless currently accepts caller-translated action and payload values, uses exact integer contention policies, distributes the summed action through a global activity-weighted allocator, and exposes aggregate exhaust and starvation counters. Its zero integer residual validates that represented transaction, not the Python local kernel.", st),
        statement("Cross-runtime evidence rule", "A comparison receives evidential weight only after naming the shared state, input translation, update rule, and invariant. Exact agreement on a shared ledger identity is meaningful; exactness in one runtime must not be reported as full implementation parity with the other.", st),

        h1("3. Invariant audit", st),
        h2("3.1 Local replenishment", st),
        body("The public Python six-neighbour transport kernel is checked for row stochasticity, stationary weights, detailed balance, global balance, local continuity, edge antisymmetry, one-edge-per-tick support growth, and convergence to the frozen-weight equilibrium. These results do not describe Tensorless R1. The current Python residuals are", st),
        equation("row=1.11&times;10<super>-16</super>, stationary=6.94&times;10<super>-18</super>, detailed=2.78&times;10<super>-17</super>,", st),
        equation("global=3.55&times;10<super>-15</super>, continuity=6.94&times;10<super>-17</super>, equilibrium L1=7.28&times;10<super>-14</super>.", st),
        body("Edge antisymmetry is exact in the reported arithmetic, the support radius grows 0 through 8 edges over ticks 0 through 8, and no speed-cone violation is observed. These are Level 2 implementation results supporting the locality theorems of Paper 1.", st),
        h2("3.2 Expanded signed ledger", st),
        body("Ordinary interior replenishment conserves its transferred total. Capacity boundaries, starvation, information erasure, and explicit joint-link operations enter separate signed accounts. In the regenerated 400-tick master chain the reported totals are 67.6694258 spillover, 16.1690471 exhaust, 23.2968474 starvation deficit, and 1.7618747&times;10<sup>-7</sup> Landauer debit. Across 18,829 boundary-clip events, the maximum expanded-ledger closure residual is 6.40&times;10<sup>-14</sup>.", st),
        statement("Conservation wording", "Ordinary interior replenishment obeys exact local conservation. When capacity boundaries, starvation, Landauer erasure, or explicit torsion-link operations occur, the expanded signed ledger remains conserved to the representation accuracy of the Python runtime.", st),
        h2("3.3 Finite quantization", st),
        body("The master chain records 3,842 carrier microcell quantizations and 1,921 joint-torsion quantizations. The maximum total-variation distance in both runtime paths is 4.2949582&times;10<sup>-10</sup>. The independent Born audit over 1,000 nine-channel states reports maximum distance 1.1979875&times;10<sup>-9</sup> and phase-probability change at floating-point roundoff. These results lie below the theorem-level finite-allocation bound.", st),

        h1("4. Current experiment suite", st),
        body("The suite contains sixteen primary experiments and a starvation subtest. The following register states what each result demonstrates.", st),
        h2("4.1 Formal and implementation experiments", st),
        bullet("<b>1. Dispersion contraction:</b> 6,000 tested states, zero violations; the zero-energy fixed dispersion is 1/6000.", st),
        bullet("<b>2. Lindblad correspondence:</b> recurrence RMSE 1.79&times;10<sup>-102</sup>, an algebraic/machine-precision agreement for the selected pure-dephasing channel.", st),
        bullet("<b>3. Closed-universe conservation:</b> final floating-point drift 7.96&times;10<sup>-14</sup> percent with no clipping in the dedicated closed test.", st),
        bullet("<b>4. Spectral-gap weights:</b> isotropic weight 1/3 and strong-shear weight 0.9891197, confirming the specified weighting law.", st),
        bullet("<b>5. Mean-field closure:</b> final mismatch, called frustration in the code, 0.0263725 after the reported relaxation schedule.", st),
        bullet("<b>6. Finite carrier-radius convergence:</b> &alpha;<sub>PP</sub>=702.6283490004513 is the positive fixed point of the four-step shell, transverse-occupation, blade-boundary, and endcap-counterterm construction derived in Paper 3 Section 6.1. It is a mathematical output of that declared carrier geometry, not a fitted datum or trajectory observable; direct substitution gives zero fixed-point residual in the evaluated binary64 arithmetic.", st),
        bullet("<b>7. Bounded depletion floor:</b> the raw law crosses the structural floor near load 99.947 and remains clipped at 0.0314 thereafter.", st),
        bullet("<b>8. Semantic-entropy ledger:</b> one erased binary distinction gives &Delta;S<sub>sem</sub>=-ln2 and &Delta;S<sub>bath</sub>/k<sub>B</sub>=ln2, so the dimensionless closure total is exactly zero in the evaluated transaction.", st),
        bullet("<b>8b. Wrong-lock starvation:</b> the test starves on tick 1 and ends at zero stored energy, exercising the signed deficit branch.", st),
        bullet("<b>9. Finite lag ceiling:</b> the implemented ratio reaches 31.8738629 at the action ceiling.", st),
        h2("4.2 Bridge and calibration experiments", st),
        bullet("<b>10. Galaxy response:</b> archived benchmark metadata in the source repository [12], built from SPARC data [8], records median RMSE 11.61 km/s for the gas-boundary source functional and 11.7156 km/s for its fixed comparison across 99 galaxies. This is not a current Level 5 empirical result and the public runtime reports it unavailable without the external tables.", st),
        bullet("<b>11. Exact carrier capacity:</b> N=1,452,997,909 is recomputed as an integer; replacing it with the continuous approximation changes the value by 1.439&times;10<sup>-6</sup> relatively.", st),
        bullet("<b>12. Born-compatible distribution:</b> finite allocation and phase invariance satisfy the declared error thresholds.", st),
        bullet("<b>13. Joint torsion Bell/CHSH:</b> S=2.8284271261, maximum correlation error 6.88&times;10<sup>-10</sup>, while the independent-local baseline remains at S=2.", st),
        bullet("<b>14. Runtime joint quantization:</b> a linked partner is pulled to the common threshold and the joint ledger closes with total-variation distance 4.29&times;10<sup>-10</sup>.", st),
        bullet("<b>15. Bare coupling:</b> inverse alpha_bare=136.7946397586; its difference from the screened CODATA inverse [11] is 0.1761 percent.", st),
        bullet("<b>16. Local replenishment continuity:</b> the complete local-kernel audit passes with the residuals reported in Section 3.1.", st),
        body("The numbering above follows the conceptual suite: the starvation case is a subtest, while local replenishment is the final primary experiment. Stored JSON may use zero-based or legacy labels internally; the experiment name is the authoritative identifier.", st),

        h1("5. Regression classes", st),
        body("A geometry or runtime change must not be judged by forcing every old number to remain unchanged. Each output is classified before comparison.", st),
        bullet("<b>Invariant:</b> conservation identities, stochasticity, detailed balance, integer totals, and declared bounds must remain exact or within their representation tolerance.", st),
        bullet("<b>Shared-contract invariant:</b> a cross-runtime comparison is valid only where both runtimes implement the same named update and receive equivalent mapped inputs.", st),
        bullet("<b>Geometry-dependent:</b> trajectories, event counts, spatial averages, relaxation rate, and plotted time series may legitimately change with node count or neighbourhood.", st),
        bullet("<b>Calibration-dependent:</b> dimensional constants change if their declared calibration inputs change; the sensitivity must match the formula.", st),
        bullet("<b>Dataset-dependent:</b> empirical scores change with inclusion rules, nuisance treatment, data revision, or missing input tables.", st),
        bullet("<b>Unexpected regression:</b> a changed invariant, an undeclared parameter drift, or a result inconsistent with its analytical dependency.", st),
        body("This classification explains why charts changed when the runtime moved from a periodic ring to the periodic cubic lattice even though the central local-conservation claim remained intact. The stored-energy trajectory is geometry-dependent; the expanded ledger closure is invariant.", st),

        h1("6. Calibration and sensitivity", st),
        h2("6.1 Parameter provenance", st),
        body("Every numerical claim must ship with a parameter ledger. Fixed values are chosen before the target dataset. Derived values follow from fixed inputs. Free values are chosen without fitting the evaluated data. Fitted values are adjusted against that data. The phrase zero fit means no independent coefficient was adjusted per galaxy; it does not mean the framework has no selected constants, source functions, or calibration choices.", st),
        h2("6.2 Sensitivity matrix", st),
        body("For output y_j and upstream quantity theta_k, report a dimensionless local sensitivity", st),
        equation("S<sub>jk</sub>=(&theta;<sub>k</sub>/y<sub>j</sub>) (&part;y<sub>j</sub>/&part;&theta;<sub>k</sub>),", st),
        body("alongside finite perturbations large enough to reveal nonlinearities and branch changes. The gravitational scale must expose its temperature dependence; the bare coupling must expose dependence on e_floor, beta, and c0; any cosmological transfer model must expose every spectrum and nuisance parameter; and any Bell gate must expose its maintenance cost, threshold, and transition width.", st),
        h2("6.3 Negative controls", st),
        bullet("Randomize spatial adjacency while preserving node marginals to test whether geometry carries information.", st),
        bullet("Replace the local kernel with its mean-field equilibrium to isolate transient locality effects.", st),
        bullet("Remove the shared torsion link to verify return to the Bell-classical baseline.", st),
        bullet("Shuffle galaxy gas fractions or boundary labels while preserving radial acceleration distributions.", st),
        bullet("Perturb the CMB oscillatory phase while preserving its envelope to test whether peak locations drive the likelihood.", st),

        h1("7. Candidate empirical programs", st),
        h2("7.1 Tensor galaxy test", st),
        body("Freeze the viscosity law, tensor contractions, gas-boundary source functional, and one global parameter ledger. Select galaxies by public quality criteria before evaluating morphology. Predict two-dimensional velocity fields and weak-lensing observables from baryonic maps, not only one-dimensional rotation curves. Compare against Newtonian baryons, a declared dark-matter halo family, and a fixed MOND/RAR baseline using the same distance, inclination, mass-to-light, and covariance treatment.", st),
        statement("Failure condition G", "Reject the present gravitational bridge if its frozen tensor model is decisively worse than the declared baseline under the pre-specified likelihood, or if residuals retain a directional lattice signature above the registered tolerance. The foundational local ledger remains a separate claim.", st),
        h2("7.2 Cosmological transfer program", st),
        body("The compact spectrum has two explicit constitutive template inputs, A<sub>osc</sub>=0.6 and ell<sub>osc</sub>=80. The local scalar kernel is dissipative and does not by itself supply acoustic phase dynamics. A CMB likelihood becomes registerable only after a dynamical transfer model specifies temperature and E-mode spectra, cross spectra, lensing, covariance, foregrounds, priors, multipole cuts, and the same nuisance freedom granted to the Planck comparison [9]. The Delta chi-squared value of +4.16 remains a compact fixed-nuisance diagnostic.", st),
        statement("Failure condition C", "For an adopted transfer model, reject the cosmological bridge if its pre-committed complete likelihood exceeds the registered adverse threshold, if required residual structure is systematic, or if competitive fit demands unregistered dataset-specific coefficients.", st),
        h2("7.3 Candidate processor-lag test", st),
        body("Adopt a progress scheduler z<sub>t+1</sub>=z<sub>t</sub>+L<sub>rest</sub>/L<sub>t</sub> and identify a measured clock, decay, transition, or propagation observable with integer crossings of z. A separate motion-to-ledger dictionary is then fixed before data collection. The selected action bounds give gamma<sub>FPM</sub>=L/L<sub>rest</sub> less than or equal to 31.8738629. This is a conditional prediction of the scheduler-plus-dictionary extension, not a prediction of the unsupplemented carrier phase update.", st),
        statement("Failure condition T", "Reject the adopted lag extension if its declared observable passes smoothly beyond the conditional finite ceiling, or departs significantly from the frozen FPM curve within the registered uncertainty model.", st),
        h2("7.4 Candidate torsion-refresh test", st),
        body("Adopt a refresh transaction for every active independent antisymmetric generator of an experimentally usable shared link. The maintenance cost is C<sub>link</sub>=n<sub>A</sub>c<sub>0</sub>. For the one-generator seed, c<sub>0</sub>=0.05, and a symmetric available action A<sup>(0)</sup>=0.5 under the declared depletion law, the conditional threshold is B<sub>*</sub>=[A<sup>(0)</sup>/(n<sub>A</sub>c<sub>0</sub>)]<sup>(4/3)</sup>-1=20.5443469. Define the laboratory variable corresponding to B, freeze the preparation distribution and transition law, and vary it while holding state preparation, analyzer settings, efficiency, and accidental background fixed.", st),
        statement("Failure condition B", "Reject the adopted torsion-refresh mechanism if high-quality entanglement retains the quantum correlation across its registered transition with no predicted dependence, or if the model violates no-signalling after all selection effects are removed.", st),

        h1("8. Analysis protocol", st),
        h2("8.1 Pre-commit before target evaluation", st),
        bullet("Scientific question and primary observable.", st),
        bullet("Dataset release, inclusion and exclusion rules, quality cuts, and stopping rule.", st),
        bullet("Forward model, units, priors, nuisance parameters, covariance, missing-data treatment, and numerical tolerances.", st),
        bullet("FPM parameter fingerprint and every baseline granted comparable flexibility.", st),
        bullet("Primary statistic, uncertainty interval, multiplicity correction, and adverse threshold.", st),
        bullet("Code and simulated-data validation completed before the final data are unblinded.", st),
        h2("8.2 Report all outcomes", st),
        body("A final report publishes parameter posteriors or confidence intervals, residual plots, calibration checks, negative controls, sensitivity results, excluded observations with reasons, and all deviations from the registered plan. Exploratory discoveries remain valuable but are labelled exploratory and tested prospectively in a later dataset.", st),
        h2("8.3 Independent reproduction", st),
        body("A decisive FPM result requires at least one reproduction that starts from the archived source and raw cited data, regenerates the machine-readable outputs and figures, and confirms the claim without private intermediate values. For the SPARC bridge specifically, the current public output marks the live local-data audit unavailable. Supplying the external tables and independently regenerating the 99-galaxy sample is therefore a required reproduction milestone.", st),

        h1("9. Failure localization", st),
        body("A modular theory should fail modularly. The following update rules prevent both overreaction and evasion.", st),
        bullet("Failure of a proof invalidates every downstream result that uses that theorem.", st),
        bullet("Failure of an implementation invariant invalidates outputs from that runtime until corrected, without automatically refuting the mathematical model.", st),
        bullet("Failure of a correspondence invalidates that bridge map, not the established equation used as its reference.", st),
        bullet("Failure of a calibration identifies a missing or incorrect dimensional dictionary and propagates only to dependent numerical scales.", st),
        bullet("Failure of a discriminating physical prediction rejects the frozen bridge or constitutive family according to the registered dependency map.", st),
        bullet("Repeated rescue by adding unregistered target-specific freedom counts against the bridge; it does not preserve the original prediction.", st),
        body("Null results also carry information. If uncertainty remains too large to distinguish FPM from a baseline, the result is inconclusive rather than supportive or adverse. The correct next step is a power analysis and improved measurement, not a change in the claim label.", st),

        h1("10. Conclusion", st),
        body("FPM has an explicit route from executable mathematics to empirical decision. Its present suite supports internal consistency for local transport, expanded signed conservation, finite quantization, and the stated computational contracts. The candidate extension programs identify the additional laws required for a Kelvin-valued temperature, paid torsion maintenance, physical clock progress, and cosmological transfer dynamics. Archived benchmark metadata, calibrated dimensional maps, and physical bridge claims retain their distinct evidence levels.", st),
        statement("Scientific programme", "Freeze each adopted extension, expose its dependency graph, and let tensor-galaxy, cosmological-transfer, processor-lag, and torsion-refresh experiments decide the corresponding bridge claims.", st),

        PageBreak(),
        h1("References", st),
        reference("[1] A. Spiker, <i>FPM Foundations</i>, Modular Paper 01, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21420508'>https://doi.org/10.5281/zenodo.21420508</a>", st),
        reference("[2] A. Spiker, <i>Executable FPM</i>, Modular Paper 02, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21420643'>https://doi.org/10.5281/zenodo.21420643</a>", st),
        reference("[3] A. Spiker, <i>Finite Carrier and Information Dynamics</i>, Modular Paper 03, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21420648'>https://doi.org/10.5281/zenodo.21420648</a>", st),
        reference("[4] A. Spiker, <i>Tensorless Exact-Ledger Sandbox</i>, Modular Paper 04, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21420650'>https://doi.org/10.5281/zenodo.21420650</a>", st),
        reference("[5] A. Spiker, <i>Phenomenological Bridges</i>, Modular Paper 05, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21420652'>https://doi.org/10.5281/zenodo.21420652</a>", st),
        reference("[6] M. D. Wilkinson et al., “The FAIR Guiding Principles for Scientific Data Management and Stewardship,” <i>Scientific Data</i> 3, 160018 (2016). <a href='https://doi.org/10.1038/sdata.2016.18'>https://doi.org/10.1038/sdata.2016.18</a>", st),
        reference("[7] IEEE, <i>IEEE Standard for Floating-Point Arithmetic</i>, IEEE 754-2019 (2019). <a href='https://doi.org/10.1109/IEEESTD.2019.8766229'>https://doi.org/10.1109/IEEESTD.2019.8766229</a>", st),
        reference("[8] F. Lelli, S. S. McGaugh, and J. M. Schombert, “SPARC: Mass Models for 175 Disk Galaxies with Spitzer Photometry and Accurate Rotation Curves,” <i>Astronomical Journal</i> 152, 157 (2016). <a href='https://doi.org/10.3847/0004-6256/152/6/157'>https://doi.org/10.3847/0004-6256/152/6/157</a>", st),
        reference("[9] Planck Collaboration, “Planck 2018 Results. VI. Cosmological Parameters,” <i>Astronomy & Astrophysics</i> 641, A6 (2020); correction 652, C4 (2021). <a href='https://doi.org/10.1051/0004-6361/201833910'>https://doi.org/10.1051/0004-6361/201833910</a>", st),
        reference("[10] J. S. Bell, “On the Einstein Podolsky Rosen Paradox,” <i>Physics Physique Fizika</i> 1, 195–200 (1964). <a href='https://doi.org/10.1103/PhysicsPhysiqueFizika.1.195'>https://doi.org/10.1103/PhysicsPhysiqueFizika.1.195</a>", st),
        reference("[11] E. Tiesinga, P. J. Mohr, D. B. Newell, and B. N. Taylor, “CODATA Recommended Values of the Fundamental Physical Constants: 2018,” <i>Reviews of Modern Physics</i> 93, 025010 (2021). <a href='https://doi.org/10.1103/RevModPhys.93.025010'>https://doi.org/10.1103/RevModPhys.93.025010</a>", st),
        reference("[12] A. Spiker, <i>Finite Possibility Mechanics Complete</i>, source repository, <a href='https://github.com/alxspiker/Finite-Possibility-Mechanics-Complete'>https://github.com/alxspiker/Finite-Possibility-Mechanics-Complete</a> (accessed July 2026).", st),
        reference("[13] A. Spiker, <i>Finite Possibility Mechanics: A Unified Information-Theoretic Framework</i>, Zenodo (2026). <a href='https://doi.org/10.5281/zenodo.21352386'>https://doi.org/10.5281/zenodo.21352386</a>", st),
    ]
    return s


if __name__ == "__main__":
    print(build_manuscript(SPEC, manuscript))
